from app.models import db, Card, environment, SCHEMA


def seed_cards():
    ace_clubs = Card(number="A", suit="clubs", value=14, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/ace_of_clubs.png", deck_id=1)
    two_clubs = Card(number="2", suit="clubs", value=2, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/2_of_clubs.png", deck_id=1)
    three_clubs = Card(number="3", suit="clubs", value=3, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/3_of_clubs.png", deck_id=1)
    four_clubs = Card(number="4", suit="clubs", value=4, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/5_of_clubs.png", deck_id=1)
    five_clubs = Card(number="5", suit="clubs", value=5, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/5_of_clubs.png", deck_id=1)
    six_clubs = Card(number="6", suit="clubs", value=6, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/6_of_clubs.png", deck_id=1)
    seven_clubs = Card(number="7", suit="clubs", value=7, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/7_of_clubs.png", deck_id=1)
    eight_clubs = Card(number="8", suit="clubs", value=8, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/8_of_clubs.png", deck_id=1)
    nine_clubs = Card(number="9", suit="clubs", value=9, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/9_of_clubs.png", deck_id=1)
    ten_clubs = Card(number="10", suit="clubs", value=10, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/10_of_clubs.png", deck_id=1)
    jack_clubs = Card(number="J", suit="clubs", value=11, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/jack_of_clubs2.png", deck_id=1)
    queen_clubs = Card(number="Q", suit="clubs", value=12, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/queen_of_clubs2.png", deck_id=1)
    king_clubs = Card(number="K", suit="clubs", value=13, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/king_of_clubs2.png", deck_id=1)
    ace_diamonds = Card(number="A", suit="diamonds", value=14, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/ace_of_diamonds.png", deck_id=1)
    two_diamonds = Card(number="2", suit="diamonds", value=2, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/2_of_diamonds.png", deck_id=1)
    three_diamonds = Card(number="3", suit="diamonds", value=3, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/3_of_diamonds.png", deck_id=1)
    four_diamonds = Card(number="4", suit="diamonds", value=4, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/4_of_diamonds.png", deck_id=1)
    five_diamonds = Card(number="5", suit="diamonds", value=5, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/5_of_diamonds.png", deck_id=1)
    six_diamonds = Card(number="6", suit="diamonds", value=6, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/6_of_diamonds.png", deck_id=1)
    seven_diamonds = Card(number="7", suit="diamonds", value=7, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/7_of_diamonds.png", deck_id=1)
    eight_diamonds = Card(number="8", suit="diamonds", value=8, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/8_of_diamonds.png", deck_id=1)
    nine_diamonds = Card(number="9", suit="diamonds", value=9, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/9_of_diamonds.png", deck_id=1)
    ten_diamonds = Card(number="10", suit="diamonds", value=10, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/10_of_diamonds.png", deck_id=1)
    jack_diamonds = Card(number="J", suit="diamonds", value=11, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/jack_of_diamonds2.png", deck_id=1)
    queen_diamonds = Card(number="Q", suit="diamonds", value=12, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/queen_of_diamonds2.png", deck_id=1)
    king_diamonds = Card(number="K", suit="diamonds", value=13, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/king_of_diamonds2.png", deck_id=1)
    ace_hearts = Card(number="A", suit="hearts", value=14, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/ace_of_hearts.png", deck_id=1)
    two_hearts = Card(number="2", suit="hearts", value=2, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/2_of_hearts.png", deck_id=1)
    three_hearts = Card(number="3", suit="hearts", value=3, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/3_of_hearts.png", deck_id=1)
    four_hearts = Card(number="4", suit="hearts", value=4, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/4_of_hearts.png", deck_id=1)
    five_hearts = Card(number="5", suit="hearts", value=5, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/5_of_hearts.png", deck_id=1)
    six_hearts = Card(number="6", suit="hearts", value=6, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/6_of_hearts.png", deck_id=1)
    seven_hearts = Card(number="7", suit="hearts", value=7, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/7_of_hearts.png", deck_id=1)
    eight_hearts = Card(number="8", suit="hearts", value=8, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/8_of_hearts.png", deck_id=1)
    nine_hearts = Card(number="9", suit="hearts", value=9, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/9_of_hearts.png", deck_id=1)
    ten_hearts = Card(number="10", suit="hearts", value=10, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/10_of_hearts.png", deck_id=1)
    jack_hearts = Card(number="J", suit="hearts", value=11, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/jack_of_hearts2.png", deck_id=1)
    queen_hearts = Card(number="Q", suit="hearts", value=12, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/queen_of_hearts2.png", deck_id=1)
    king_hearts = Card(number="K", suit="hearts", value=13, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/king_of_hearts2.png", deck_id=1)
    ace_spades = Card(number="A", suit="spades", value=14, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/ace_of_spades.png", deck_id=1)
    two_spades = Card(number="2", suit="spades", value=2, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/2_of_spades.png", deck_id=1)
    three_spades = Card(number="3", suit="spades", value=3, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/3_of_spades.png", deck_id=1)
    four_spades = Card(number="4", suit="spades", value=4, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/4_of_spades.png", deck_id=1)
    five_spades = Card(number="5", suit="spades", value=5, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/5_of_spades.png", deck_id=1)
    six_spades = Card(number="6", suit="spades", value=6, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/6_of_spades.png", deck_id=1)
    seven_spades = Card(number="7", suit="spades", value=7, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/7_of_spades.png", deck_id=1)
    eight_spades = Card(number="8", suit="spades", value=8, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/8_of_spades.png", deck_id=1)
    nine_spades = Card(number="9", suit="spades", value=9, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/9_of_spades.png", deck_id=1)
    ten_spades = Card(number="10", suit="spades", value=10, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/10_of_spades.png", deck_id=1)
    jack_spades = Card(number="J", suit="spades", value=11, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/jack_of_spades2.png", deck_id=1)
    queen_spades = Card(number="Q", suit="spades", value=12, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/queen_of_spades2.png", deck_id=1)
    king_spades = Card(number="K", suit="spades", value=13, card_art="https://dudemastersongbucket.s3.amazonaws.com/card+images/king_of_spades2.png", deck_id=1)
    
    db.session.add(ace_clubs)
    db.session.add(ace_hearts)
    db.session.add(ace_diamonds)
    db.session.add(ace_spades)
    db.session.add(two_clubs)
    db.session.add(three_clubs)
    db.session.add(four_clubs)
    db.session.add(five_clubs)
    db.session.add(six_clubs)
    db.session.add(seven_clubs)
    db.session.add(eight_clubs)
    db.session.add(nine_clubs)
    db.session.add(ten_clubs)
    db.session.add(jack_clubs)
    db.session.add(queen_clubs)
    db.session.add(king_clubs)
    db.session.add(two_diamonds)
    db.session.add(three_diamonds)
    db.session.add(four_diamonds)
    db.session.add(five_diamonds)
    db.session.add(six_diamonds)
    db.session.add(seven_diamonds)
    db.session.add(eight_diamonds)
    db.session.add(nine_diamonds)
    db.session.add(ten_diamonds)
    db.session.add(jack_diamonds)
    db.session.add(queen_diamonds)
    db.session.add(king_diamonds)
    db.session.add(two_hearts)
    db.session.add(three_hearts)
    db.session.add(four_hearts)
    db.session.add(five_hearts)
    db.session.add(six_hearts)
    db.session.add(seven_hearts)
    db.session.add(eight_hearts)
    db.session.add(nine_hearts)
    db.session.add(ten_hearts)
    db.session.add(jack_hearts)
    db.session.add(queen_hearts)
    db.session.add(king_hearts)
    db.session.add(two_spades)
    db.session.add(three_spades)
    db.session.add(four_spades)
    db.session.add(five_spades)
    db.session.add(six_spades)
    db.session.add(seven_spades)
    db.session.add(eight_spades)
    db.session.add(nine_spades)
    db.session.add(ten_spades)
    db.session.add(jack_spades)
    db.session.add(queen_spades)
    db.session.add(king_spades)
    db.session.commit()


# Uses a raw SQL query to TRUNCATE or DELETE the users table. SQLAlchemy doesn't
# have a built in function to do this. With postgres in production TRUNCATE
# removes all the data from the table, and RESET IDENTITY resets the auto
# incrementing primary key, CASCADE deletes any dependent entities.  With
# sqlite3 in development you need to instead use DELETE to remove all data and
# it will reset the primary keys for you as well.
def undo_cards():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.cards RESTART IDENTITY CASCADE;")
    else:
        db.session.execute("DELETE FROM cards")
        
    db.session.commit()