"""empty message

Revision ID: fbd5f77a5df5
Revises: ffdc0a98111c
Create Date: 2023-01-30 23:15:07.579400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbd5f77a5df5'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('default_deck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_art', sa.String(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('suit', sa.String(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('card_art', sa.String(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=True),
    sa.Column('deck_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['default_deck.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_name', sa.String(length=20), nullable=False),
    sa.Column('card_art', sa.String(), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timer', sa.Integer(), nullable=False),
    sa.Column('game_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_default_deck',
    sa.Column('players', sa.Integer(), nullable=False),
    sa.Column('deck', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deck'], ['default_deck.id'], ),
    sa.ForeignKeyConstraint(['players'], ['users.id'], ),
    sa.PrimaryKeyConstraint('players', 'deck')
    )
    op.create_table('card_decks',
    sa.Column('cards', sa.Integer(), nullable=False),
    sa.Column('decks', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cards'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['decks'], ['custom_decks.id'], ),
    sa.PrimaryKeyConstraint('cards', 'decks')
    )
    op.create_table('player_game',
    sa.Column('player1_id', sa.Integer(), nullable=False),
    sa.Column('game', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player1_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('player1_id', 'game')
    )
    op.add_column('users', sa.Column('profile_img', sa.String(), nullable=True))
    op.add_column('users', sa.Column('wins', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('losses', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'losses')
    op.drop_column('users', 'wins')
    op.drop_column('users', 'profile_img')
    op.drop_table('player_game')
    op.drop_table('card_decks')
    op.drop_table('player_default_deck')
    op.drop_table('games')
    op.drop_table('custom_decks')
    op.drop_table('cards')
    op.drop_table('default_deck')
    # ### end Alembic commands ###