"""empty message

Revision ID: 45d2b1aa4de6
Revises: fbd5f77a5df5
Create Date: 2023-01-31 01:24:03.690279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d2b1aa4de6'
down_revision = 'fbd5f77a5df5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_game')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_game',
    sa.Column('player1_id', sa.INTEGER(), nullable=False),
    sa.Column('game', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['game'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player1_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('player1_id', 'game')
    )
    # ### end Alembic commands ###