"""empty message

Revision ID: eb5c323799fe
Revises: 45d2b1aa4de6
Create Date: 2023-02-01 22:11:58.678594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb5c323799fe'
down_revision = '45d2b1aa4de6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_default_deck')
    op.add_column('users', sa.Column('deck_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'default_deck', ['deck_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'deck_id')
    op.create_table('player_default_deck',
    sa.Column('players', sa.INTEGER(), nullable=False),
    sa.Column('deck', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['deck'], ['default_deck.id'], ),
    sa.ForeignKeyConstraint(['players'], ['users.id'], ),
    sa.PrimaryKeyConstraint('players', 'deck')
    )
    # ### end Alembic commands ###